### ISSUE TITLE
What is $DISPLAY varibale

### ISSUE THREAD

**Issue by knrt10** [ekiourk/docker-ns2#2]
Hey when you are using `docker run -it -v $PWD/ns-simple.tcl:/ns-simple.tcl -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY ekiourk/ns2 bash`

What is your `$DISPLAY` variable?

I am not able to open GUI for nam. Can you please help. Below the output is given
![screen shot 2019-01-20 at 11 04 54 pm](https://user-images.githubusercontent.com/24803604/51442906-d78f9a80-1d07-11e9-8d77-c9990665a78c.png)

**Comment by apsknight** [comment]
Hey @knrt10,

Did you find any solution for this? I'm also facing the same problem.

**Comment by knrt10** [comment]
@apsknight yes, try this https://github.com/moby/moby/issues/8710

**Comment by knrt10** [comment]
Solved it, refer to above comment.
